### ISSUE TITLE
Translate article

### ISSUE THREAD

**Issue by SofiaOganova** [Haulmont/jmix-website-content#1]
Please translate into Italian: https://github.com/Haulmont/jmix-website-content/tree/master/Content/Blog/Jmix%20-%20the%20future%20of%20CUBA%20Platform

**Comment by pfurini** [comment]
The article has already been translated here: https://github.com/cuba-platform/website-content/blob/master/Blog/Jmix%20-%20the%20future%20of%20CUBA%20Platform%20IT.md

Closing this..
