### ISSUE TITLE
[Add-On] entity-soft-reference

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-website-content#32]
### Add-on Name

entity-soft-reference

### Github Repository

https://github.com/mariodavid/jmix-entity-soft-reference

**Comment by knstvk** [comment]
Created proxy repos.
Please create a PR for jmix-bom.

**Comment by mariodavid** [comment]
@knstvk: done - see: https://github.com/Haulmont/jmix-bom/pull/24

**Comment by knstvk** [comment]
@mariodavid - the PR is merged to BOM. Please create PR for Marketplace content.

**Comment by mariodavid** [comment]
@knstvk @SofiaOganova, done: https://github.com/Haulmont/jmix-website-content/pull/36

**Comment by knstvk** [comment]
@mariodavid - could you create a PR for BOM release_1_2 branch?
Then we'll finally publish the add-on.
