### ISSUE TITLE
MinIO File Storage Addon

### ISSUE THREAD

**Issue by godlewski-dm** [Haulmont/jmix-website-content#35]
### Add-on Name

MinIO File Storage

### Github Repository

https://github.com/warhammster/jmix-miniofs

**Comment by knstvk** [comment]
Thank you for the contribution, we'll notify you as soon as proxy repositories are ready.

**Comment by knstvk** [comment]
Proxy repos are ready. Plz create PRs for marketplce content and for jmix-bom.

**Comment by godlewski-dm** [comment]
@knstvk done

**Comment by knstvk** [comment]
Sorry for not telling you earlier, but you should change the artefact group and base package of the add-on, to not confuse with the add-ons made by the core team.

Please rebuild the add-on and re-submit the PR.

**Comment by godlewski-dm** [comment]
@knstvk changed. Please check https://github.com/Haulmont/jmix-bom/pull/28

**Comment by knstvk** [comment]
Thanks, merged!
Adding to marketplace is in progress.

**Comment by knstvk** [comment]
Done: https://www.jmix.io/marketplace/minio-file-storage/
