### ISSUE TITLE
[Add-On] Huawei OBS File Storage

### ISSUE THREAD

**Issue by pierresj** [Haulmont/jmix-website-content#39]
### Add-on Name

Jmix Huawei OBS File Storage

### Github Repository

https://github.com/pierresj/jmix-huaweifs

**Comment by pierresj** [comment]
# Huawei OBS File Storage
# 华为云 文件存储

A FileStorage implementation that stores data in Huawei OBS.
FileStorage（文件存储）接口的一个实现，将文件存在 华为云OBS 中。

## Overview 
## 介绍

The add-on provides a FileStorage implementation that stores data backed by file references in [Huawei OBS].
该扩展插件提供了一个 FileStorage 的实现，将文件引用数据存储在 [Huawei OBS]

**Comment by knstvk** [comment]
Hi @pierresj 
Should we proceed with your add-on or you have changed your mind?
