### ISSUE TITLE
[Add-on]Huawei OBS File Storage 

### ISSUE THREAD

**Issue by pierresj** [Haulmont/jmix-website-content#41]
### Add-on Name

jmix-huaweifs

### Github Repository

https://github.com/pierresj/jmix-huaweifs

**Comment by pierresj** [comment]
A FileStorage implementation  that stores data backed by file references in HuaweiCloud Object Storage Service(OBS)。
This addon just is  appropriate for China developers,so we won’t provide Chinese description.[https://www.huaweicloud.com/product/obs.html](url)

**Comment by knstvk** [comment]
@pierresj Why do you create a second issue and immediately close it?

**Comment by pierresj** [comment]
@knstvk Sorry, I have fixed some bugs and reopen it.

**Comment by knstvk** [comment]
Thanks! 
We'll proceed with publishing in the next few days.

**Comment by knstvk** [comment]
Please fix the README: the dependency should be `implementation 'io.github.pierresj:jmix-huaweifs-starter:1.0.7'` (not `1.0.7-RELEASE`)

**Comment by pierresj** [comment]
I have fixed the README.

**Comment by knstvk** [comment]
Please create a PR for BOM in release_1_2 branch: https://github.com/jmix-framework/jmix/blob/release_1_2/jmix-bom/bom.gradle

**Comment by pierresj** [comment]
I created the PR for BOM in release_1_2 branch: [https://github.com/jmix-framework/jmix/pull/646](https://github.com/jmix-framework/jmix/pull/646)

**Comment by pierresj** [comment]
@SofiaOganova 
Documentation [https://github.com/pierresj/jmix-huaweifs/blob/master/README.md](https://github.com/pierresj/jmix-huaweifs/blob/master/README.md)
Bugtracker [https://github.com/pierresj/jmix-huaweifs/issues](https://github.com/pierresj/jmix-huaweifs/issues)
Github [https://github.com/pierresj/jmix-huaweifs](https://github.com/pierresj/jmix-huaweifs)
Version updated at Mar 15, 2022
Versions 1.1-1.2
Category Integration
Author name PierreShi
