### ISSUE TITLE
[Add-On] Tencent COS FileStorage

### ISSUE THREAD

**Issue by 22218lionel** [Haulmont/jmix-website-content#45]
### Add-on Name

jmixcn-tencentfs

### Github Repository

https://github.com/cubacn/jmix-tencentfs

**Comment by 22218lionel** [comment]
A FileStorage implementation that stores data backed by file references in Tencent Cloud Object Storage(COS).
This addon just is appropriate for China developers,so we just provide Chinese description.
https://cloud.tencent.com/document/product/436

**Comment by knstvk** [comment]
Thanks! 
We'll proceed with publishing in the next few days.

**Comment by knstvk** [comment]
Please set up CI and create a release as described at https://docs.jmix.io/jmix/1.2/publish-add-on.html#continuous-integration
It should produce artefacts here: https://github.com/orgs/cubacn/packages?repo_name=jmix-tencentfs

**Comment by 22218lionel** [comment]
> Please set up CI and create a release as described at https://docs.jmix.io/jmix/1.2/publish-add-on.html#continuous-integration It should produce artefacts here: https://github.com/orgs/cubacn/packages?repo_name=jmix-tencentfs

I created a release and published add-on artifacts to the designated GitHub Packages.

**Comment by knstvk** [comment]
Please create a PR for BOM in release_1_2 branch: https://github.com/jmix-framework/jmix/blob/release_1_2/jmix-bom/bom.gradle

**Comment by 22218lionel** [comment]
I created a PR for BOM in release_1_2 branch: https://github.com/jmix-framework/jmix/pull/650

**Comment by 22218lionel** [comment]
Documentation https://github.com/cubacn/jmix-tencentfs/blob/master/README.md
Bugtracker https://github.com/cubacn/jmix-tencentfs/issues
Github https://github.com/cubacn/jmix-tencentfs
Version updated at March 16, 2022
Versions 1.1-1.2
Category Integration
Author name JmixCn Team

**Comment by 22218lionel** [comment]
Hi @SofiaOganova,I added the needed information.
