### ISSUE TITLE
[Add-On] Qiniu Kodo File Storage

### ISSUE THREAD

**Issue by pierresj** [Haulmont/jmix-website-content#49]
### Add-on Name

jmix-qiniufs

### Github Repository

https://github.com/pierresj/jmix-qiniufs

**Comment by pierresj** [comment]
A FileStorage implementation that stores data backed by file references in [QIniu Kodo](https://www.qiniu.com/products/kodo).
This addon just is appropriate for China developers,so we just provide Chinese description.

**Comment by knstvk** [comment]
Please fix the README: the dependency should be `implementation 'io.github.pierresj:jmix-qiniufs-starter:1.0.2'` (not 1.0.0-RELEASE)

**Comment by pierresj** [comment]
I have fixed the README.

**Comment by knstvk** [comment]
Please create a PR for BOM in release_1_2 branch: https://github.com/jmix-framework/jmix/blob/release_1_2/jmix-bom/bom.gradle

**Comment by pierresj** [comment]
I created the PR for BOM in release_1_2 branch: [https://github.com/jmix-framework/jmix/pull/646](https://github.com/jmix-framework/jmix/pull/646)

**Comment by pierresj** [comment]
@SofiaOganova 
Documentation [https://github.com/pierresj/jmix-qiniufs/blob/master/README.md](https://github.com/pierresj/jmix-qiniufs/blob/master/README.md)
Bugtracker [https://github.com/pierresj/jmix-qiniufs/issues](https://github.com/pierresj/jmix-qiniufs/issues)
Github [https://github.com/pierresj/jmix-qiniufs](https://github.com/pierresj/jmix-qiniufs)
Version updated at Mar 15, 2022
Versions 1.1-1.2
Category Integration
Author name PierreShi
