### ISSUE TITLE
[Add-On] Duration Field

### ISSUE THREAD

**Issue by pbaris** [Haulmont/jmix-website-content#50]
### Add-on Name

Duration Field

### Github Repository

https://github.com/pbaris/jmix-duration-field

**Comment by knstvk** [comment]
Thank you!
Please create a PR for BOM in release_1_2 branch: https://github.com/jmix-framework/jmix/blob/release_1_2/jmix-bom/bom.gradle

**Comment by pbaris** [comment]
I created a new PR for BOM
