### ISSUE TITLE
[Add-On] Image Cropper

### ISSUE THREAD

**Issue by GuoRuiLv** [Haulmont/jmix-website-content#56]
### Add-on Name

Image Cropper

### Github Repository

https://github.com/cubacn/jmix-ImageCropper

**Comment by knstvk** [comment]
Hi @GuoRuiLv 
Thank you for the contribution! 
We'll set up proxy repos for your add-on and let you know.

**Comment by SofiaOganova** [comment]
@GuoRuiLv Hi. Could you please tell me who to set the author of this add-on?

**Comment by GuoRuiLv** [comment]
Hi @SofiaOganova ,
The author of projects belong to cubacn account  should be 'JmixCn Team' .   
By the way,  when will  other projects we created publish? Include jmix-alifs,jmix-tencentfs,jmix-baidufs, jmix-huaweifs,jmix-qiniufs. 
The author of  jmix-huaweifs,jmix-qiniufs should be the project owner.

**Comment by SofiaOganova** [comment]
Greetings @GuoRuiLv,
Thank you!
We need information to post add-ons on the website.
Could you please share the following information about add-ons?
Documentation (url)
Bugtracker (url)
Github (url)
Version updated at (modification date)
Versions
Platform versions (compatible platform version)
Category
Author name
You can see a sample of the content at https://www.jmix.cn/marketplace/.

**Comment by GuoRuiLv** [comment]
Hi @SofiaOganova ,
We have created issues and  did required  stuffs  following [doc](https://docs.jmix.io/jmix/publish-add-on.html) for the addons I mentioned.
Issue links of these addons:
https://github.com/jmix-framework/jmix-website-content/issues/46
https://github.com/jmix-framework/jmix-website-content/issues/45
https://github.com/jmix-framework/jmix-website-content/issues/49
https://github.com/jmix-framework/jmix-website-content/issues/43
https://github.com/jmix-framework/jmix-website-content/issues/41

If the information is not enough for publishing, I will  replenish needed information on relevant issue. 
And maybe the  Issue Template should be refined so that addon author can fill all needed information when creating issue for publishing addon.

**Comment by GuoRuiLv** [comment]
Documentation https://github.com/cubacn/jmix-ImageCropper/blob/master/ImageCropper/README.md
Bugtracker  https://github.com/cubacn/jmix-ImageCropper/issues
Github  https://github.com/cubacn/jmix-ImageCropper/
Version updated at  May 06, 2022
Versions  1.1-1.2
Category   UI,Tools
Author name  JmixCn Team

**Comment by SofiaOganova** [comment]
Hi @GuoRuiLv,
Thank you!

We need the following content to publish add-ons on [www.jmix.cn](http://www.jmix.cn/):
Name
Slug
Short Description 
Description 
Documentation (url)
Bugtracker (url)
Github (url)
Version updated at (modification date)
Versions
Platform versions (compatible platform versions)
Category
Author name

You can use this list in the future to generate content for the website.

**Comment by GuoRuiLv** [comment]
Okey ,thank you.
