### ISSUE TITLE
[Add-On] Menu Editor

### ISSUE THREAD

**Issue by daring2** [Haulmont/jmix-website-content#61]
### Add-on Name

Menu Editor

### Github Repository

https://github.com/daring2/jmix-menu-editor

**Comment by knstvk** [comment]
Thank you for the contribution!
Could you create a simple demo application that shows the add-on in action?
My quick experiment didn't play well.

**Comment by daring2** [comment]
Thank you for the excellent Jmix platform!

I tested the add-on in the standard [jmix-petclinic](https://github.com/daring2/jmix-petclinic) project. As far as I see it works correctly except of the problem with dynamic menu item `myVisits`. This item is not defined in `menu.xml` so it is not automatically added to the menu configuration. Also I've created an empty project [jmix-menu-editor-test](https://github.com/daring2/jmix-menu-editor-test) from an IDEA template, it seems that the add-on works in this project as well.

What problems have you noticed in your project? I can try to reproduce and fix them.

**Comment by knstvk** [comment]
I've created a menu and assign it to some role. Then gave this role to a user with minimal UI permissions. Logged in as that  user - nothing in the menu.
Perhaps I used it not as expected.
Could you explain what is the purpose of the add-on in README and give a complete use case?

**Comment by daring2** [comment]
> I've created a menu and assign it to some role. Then gave this role to a user with minimal UI permissions. Logged in as that user - nothing in the menu.

The add-on doesn't assign or change user permissions so this behaviour is expected and correct.

I updated the add-on description and added a list of main functions:
- allow to change menu structure and properties of menu items (caption, shortcut, icon, etc) using the administration screens at runtime.
- allow to use multiple main menus with different structure for different use groups.

These functions describe add-on use cases:
- administrators need to change the main menu at runtime without development and deployment of a new application version.
- different user groups need main menus with different structure, these menus must be configurable.

Actually some of our customers asked about these functions so I implemented them in this add-on.

**Comment by knstvk** [comment]
Thank you for the explanation.

I still think we need more information in README. Please add:
- Intended use cases (as you explained in the comment above)
- A **Usage example** section with a step-by-step guide of how to implement at least one simple use case. Something like "1. Login as admin. 2. Open ..., create .... 3. Login as .... You will see ...".

It will help a lot for popularizing the add-on.

**Comment by daring2** [comment]
I agree, it will be useful for add-on users. I will add this information soon.

**Comment by daring2** [comment]
I updated README and added the sections "Use cases" and "Getting started".

**Comment by knstvk** [comment]
Thanks! Now it's much more clear.
Let's proceed with publication when we release 1.5.0 in the end of Feb. We are not going to release patches of 1.4 anymore, so adding the add-on to the BOM v.1.4 doesn't make sense. You will have to build a new release based on 1.5.0 and submit a PR to https://github.com/jmix-framework/jmix with BOM changes as explained at https://docs.jmix.io/jmix/publish-add-on.html#update-bom.
Please provide also a description for marketplace as explained at https://docs.jmix.io/jmix/publish-add-on.html#submit-description.

**Comment by daring2** [comment]
OK, I will test the add-on with jmix-1.5.0 and create PRs for BOM and a marketplace descrption. Thank you for your help and advices!

**Comment by knstvk** [comment]
We are going to release 1.5.1 this week. Would be great to have your add-on in the BOM and on the marketplace.

**Comment by daring2** [comment]
Great! I created PRs:
- https://github.com/jmix-framework/jmix-website-content/pull/62
- https://github.com/jmix-framework/jmix/pull/1544

**Comment by SofiaOganova** [comment]
The add-on has been published https://www.jmix.io/marketplace/menu-editor/

**Comment by daring2** [comment]
Thank you!
