### ISSUE TITLE
[Add-on] TinyMCE Editor

### ISSUE THREAD

**Issue by pbaris** [Haulmont/jmix-website-content#63]
### Add-on Name

Jmix TinyMCE Editor

### Github Repository

https://github.com/pbaris/jmix-tinymce

**Comment by knstvk** [comment]
Thank you @pbaris 
We'll proxy the add-on artifact repository and let you know. Meanwhile, please create a PR for including the add-on in BOM.

**Comment by pbaris** [comment]
@knstvk done, see: jmix-framework/jmix#3229

**Comment by knstvk** [comment]
Done: https://www.jmix.io/marketplace/jmix-tinymce/
