### ISSUE TITLE
[Add-On] Exception Handler Youtrack Integration

### ISSUE THREAD

**Issue by dogacgulacan** [Haulmont/jmix-website-content#68]
### Add-on Name

ExceptionHandlerYouTrack

### Github Repository

https://github.com/dogacgulacan/ExceptionHandlerYouTrack

**Comment by dogacgulacan** [comment]
When a runtime exception and navigation exception occurs in this add-on program, it contacts Youtrack and creates an issue.

**Comment by knstvk** [comment]
Hi @dogacgulacan 
Thank you for the contribution!

Your solution is certainly useful, but it seems too specific and at the same time too simple to be a public add-on.
Please consider publishing it as a recipe at [Community Solutions and Guides](https://forum.jmix.io/c/community/40).
